#!/bin/bash

${JMETER_HOME}/bin/jmeter-server -Dserver_port=60000 -Dclient.rmi.localport=60000 -Dserver.rmi.localport=60000 -Djava.rmi.server.hostname=`curl -s http://169.254.169.254/latest/meta-data/public-ipv4`
